language: c
os:
 - linux
 - osx
compiler: clang
install:
 - ulimit -c unlimited -S
 - make all
script: make test
after_failure:
 - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
 - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
